# Generated by Django 5.1.4 on 2024-12-10 03:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0002_alter_firefighters_rank_alter_firefighters_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='firestation',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='firestation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='firestation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True),
        ),
    ]
